### ISSUE TITLE
3.0 TRACKER?

### ISSUE THREAD

**Issue by tacticalbacon89** [Yersi88/WMR-and-Vive-Tracker#1]
have you found any work arounds or found any way to make using 3.0 tracker work.

 i saw on reddit where 3.0 tracker is said to work so that was the one i bought.  before i saw this post.

**Comment by tacticalbacon89** [comment]
@Yersi88

**Comment by Yersi88** [comment]
You can try but for me 3.0 tracker just drifts more and won't work over passive cable.
