### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by Balticwh4le** [Yersi88/WMR-and-Vive-Tracker#4]
Just wondering if this still works, since I will have to buy a tracker for this. Also. Since steamvr now tracks the headset, is ovr space calibrator no longer needed? Will it boot up like any normal headset and already have the controllers where they are supposed to be from the start?

**Comment by Yersi88** [comment]
AFAIK, it still works. All your other questions are answered in the Readme, which you'd know if you'd, well, read it. No space cal required.
